---
abstract: 'enable to dispatch to the Catalyst via 404 handler.'
author:
  - 'Hironori Yoshida <yoshida@cpan.org>'
build_requires:
  Test::Base: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Plugin-Engine-FastCGI-Lighttpd
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
  perl: 5.8.0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.0.1
